<a href="https://colab.research.google.com/github/Anjalee01/Python-For-Mathematicians/blob/main/Numpy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

Numpy is multidimentional array library

Can store all type of data(1 Dimentional, 2 Dimentionl and 3Dimentional) like **List**

# **Difference between Numpy and List**

Numpy is fast multidimentional used for array manipulation

Low level implimented libraries of Numpy like C and photran they are way faster than python

Numpy is Faster than Metlab

Numpy Can be used in Machine Learning

In [ ]:
list1 = [1,2,3]
list2 = [2,4,5]
print(list1+list2)

[1, 2, 3, 2, 4, 5]


In [ ]:
list1 = [1,2,3]
list2 = [2,4,5,4]
results = []
results.append(list1[0] + list2[0])
results.append(list1[1] + list2[1])
results.append(list1[2] + list2[2])
print(results)

[3, 6, 8]


In [ ]:
list1 = [1, 2, 3]
list2 = [2, 4, 5]

# Initialize an empty list to store the results
result = []

# Use a simple for loop for element-wise addition
for i in range(len(list1)):
    result.append(list1[i] + list2[i])

print(result)  # Output: [3, 6, 8]


[3, 6, 8]


In [ ]:
#alias(like a nickname)
import numpy as np
print(np.__version__)

1.26.4


**1. Faster Execution**

NumPy arrays are much faster than Python lists for numerical computations.

**2. Easy Mathematical Operations**

You can directly perform element-wise operations without writing loops

In [ ]:
a = np.array([1,2,3])
print(a+a)

[2 4 6]


In [ ]:
import time
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()
result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])
end = time.time()
print("loop addition time:", end - start)

# Adding with NumPy
array1 = np.array(list1)
array2 = np.array(list2)

start = time.time()
result = array1 + array2
end = time.time()
print("loop addition time:", end - start)




loop addition time: 0.27383995056152344
loop addition time: 0.005396127700805664


In [ ]:
def print_array_details(a):
  print(f"shape: {a.shape}")

a = np.array([1,2,3,4,5,6,7,8])
print(a)
print_array_details(a)

[1 2 3 4 5 6 7 8]
shape: (8,)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a2 = a.reshape([3,4])
print(a2)
print(a2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
#Then a 3d array from our 1d array
a = np.array([1,2,3,4,5,6,7,8])
a3 = a.reshape([2,2,2])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9, 10,11,12])
a4 = a.reshape([2,3,2])
print(a4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
zeros_array = np.zeros([2, 3])
print(type(zeros_array))   # <class 'numpy.ndarray'>
print(zeros_array.dtype)

<class 'numpy.ndarray'>
float64


In [ ]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

print(np.empty([3,3]))

[[4.9812044e-310 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [ ]:
print(np.random.random((2,2)))
print(np.linspace(2,11,5)) # five numbers range 2-10
print(np.arange(2,10,2)) # 2 being the step size

[[0.41578512 0.04181155]
 [0.01542819 0.85164808]]
[ 2.    4.25  6.5   8.75 11.  ]
[2 4 6 8]


In [ ]:
a = np.array((1,2,3,4,5,6,7,8))
print(a[-2])
print(a[3:7]) # a slice

7
[4 5 6 7]


In [ ]:
print(a*2)
print(a/2)

[ 2  4  6  8 10 12 14 16]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


**Accessing/Changing specific elements, rows, columns, etc**


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],
 [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# something fancy [startindex:endindex:stepsize]

a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])

a[0, 1:-1: 3]

array([2, 5])

In [ ]:
a[0,5] = 20

#: means select all rows, 2 means select column 2 across all rows
a[:,2] = [1,2]
print(a)


[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 13 14]]


In [5]:
a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14],
              [15,16,17,18,19,20,21]])
a[1 :,2] = [22] # select row 1 and 2 and in column 2 replace values with 22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 22 11 12 13 14]
 [15 16 22 18 19 20 21]]


**3D example**

In [6]:
b = np.array([[[1,2],[3,4]],  [[5,6],[7,8]]]) #shape (2,2,2)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# Get specific element # block, row, element(column)
b[0,1,0]

3

In [8]:
# replace : select all blocks, 1 select second row of each block, : all elements in the second row
b[:,0,:] =[[9,9],[8,8]]
print(b)

[[[9 9]
  [3 4]]

 [[8 8]
  [7 8]]]


In [9]:
# Any other number (full Return a new array of given shape and type, filled with fill_value.)
import numpy as np
np.full((2,2), [0,99])

array([[ 0, 99],
       [ 0, 99]])

In [10]:
# Random decimal numbers between 0 and 1, try two arguments, first will give you an error and then do it with tuple
np.random.random(6)

array([0.16642422, 0.05737825, 0.13750231, 0.86322473, 0.33022168,
       0.03253928])

In [11]:
#Random Integer values
#low: The inclusive lower bound of the random integers.
#high: The exclusive upper bound of the random integers (if None, it will be assumed to be equal to low, and the result will be 0).
#size: The shape of the output array.

np.random.randint(-4,2 , size=(3,2))

array([[-1,  0],
       [-4, -3],
       [-1, -2]])

**An identity matrix is a square matrix where: The diagonal elements are 1. All off-diagonal elements are 0.**

In [12]:
# The identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

a: The input array that you want to repeat elements from. repeats: The number of times each element (or block of elements) should be repeated. axis: The axis along which to repeat the values. If None, the array is flattened before repeating.

In [13]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
r4 = np.repeat(arr, 2, axis=0)
print(r4)

[[1 2]
 [1 2]
 [3 4]
 [3 4]
 [5 6]
 [5 6]]


Be careful when copying arrays!!!

In [15]:
#shallow copy
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [16]:
#deep copy
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [17]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a*b)

[ 5 12 21 32]
