<a href="https://colab.research.google.com/github/Anjalee01/Python-For-Mathematicians/blob/main/Numpy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

Numpy is multidimentional array library

Can store all type of data(1 Dimentional, 2 Dimentionl and 3Dimentional) like **List**

# **Difference between Numpy and List**

Numpy is fast multidimentional used for array manipulation

Low level implimented libraries of Numpy like C and photran they are way faster than python

Numpy is Faster than Metlab

Numpy Can be used in Machine Learning

In [ ]:
list1 = [1,2,3]
list2 = [2,4,5]
print(list1+list2)

[1, 2, 3, 2, 4, 5]


In [ ]:
list1 = [1,2,3]
list2 = [2,4,5,4]
results = []
results.append(list1[0] + list2[0])
results.append(list1[1] + list2[1])
results.append(list1[2] + list2[2])
print(results)

[3, 6, 8]


In [ ]:
list1 = [1, 2, 3]
list2 = [2, 4, 5]

# Initialize an empty list to store the results
result = []

# Use a simple for loop for element-wise addition
for i in range(len(list1)):
    result.append(list1[i] + list2[i])

print(result)  # Output: [3, 6, 8]


[3, 6, 8]


In [ ]:
#alias(like a nickname)
import numpy as np
print(np.__version__)

1.26.4


**1. Faster Execution**

NumPy arrays are much faster than Python lists for numerical computations.

**2. Easy Mathematical Operations**

You can directly perform element-wise operations without writing loops

In [ ]:
a = np.array([1,2,3])
print(a+a)

[2 4 6]


In [ ]:
import time
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()
result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])
end = time.time()
print("loop addition time:", end - start)

# Adding with NumPy
array1 = np.array(list1)
array2 = np.array(list2)

start = time.time()
result = array1 + array2
end = time.time()
print("loop addition time:", end - start)




loop addition time: 0.27383995056152344
loop addition time: 0.005396127700805664


In [ ]:
def print_array_details(a):
  print(f"shape: {a.shape}")

a = np.array([1,2,3,4,5,6,7,8])
print(a)
print_array_details(a)

[1 2 3 4 5 6 7 8]
shape: (8,)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a2 = a.reshape([3,4])
print(a2)
print(a2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
#Then a 3d array from our 1d array
a = np.array([1,2,3,4,5,6,7,8])
a3 = a.reshape([2,2,2])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9, 10,11,12])
a4 = a.reshape([2,3,2])
print(a4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
zeros_array = np.zeros([2, 3])
print(type(zeros_array))   # <class 'numpy.ndarray'>
print(zeros_array.dtype)

<class 'numpy.ndarray'>
float64


In [ ]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

print(np.empty([3,3]))

[[4.9812044e-310 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [ ]:
print(np.random.random((2,2)))
print(np.linspace(2,11,5)) # five numbers range 2-10
print(np.arange(2,10,2)) # 2 being the step size

[[0.41578512 0.04181155]
 [0.01542819 0.85164808]]
[ 2.    4.25  6.5   8.75 11.  ]
[2 4 6 8]


In [ ]:
a = np.array((1,2,3,4,5,6,7,8))
print(a[-2])
print(a[3:7]) # a slice

7
[4 5 6 7]


In [ ]:
print(a*2)
print(a/2)

[ 2  4  6  8 10 12 14 16]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [ ]:
!git config --global user.name "Your GitHub Username"
!git config --global user.email "your.email@example.com"


In [ ]:
!git clone https://github.com/Anjalee01/Python-For-Mathematicians


Cloning into 'Python-For-Mathematicians'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 21 (delta 7), reused 19 (delta 5), pack-reused 0 (from 0)
Receiving objects: 100% (21/21), 5.13 KiB | 1.28 MiB/s, done.
Resolving deltas: 100% (7/7), done.


In [ ]:
!cp /content/Numpy_Notes.ipynb /content/Python-For-Mathematicians/


cp: cannot stat '/Numpy_Notes.ipynb': No such file or directory


In [ ]:
!ls


Python-For-Mathematicians  sample_data
